services:
  backend:
    build: ./backend
    container_name: flask-api
    ports:
      - "5000:5000"
    networks:
      - minha-rede

  frontend:
    build: ./frontend
    container_name: react-nginx
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - minha-rede

  redis:
    image: "redis:alpine"

networks:
  minha-rede:
    driver: bridge
